package com.itverse.futuris

const val EXTRA_COMPOSANT_SELECTED = "EXTRA_COMPOSANT_SELECTED"
const val EXTRA_PROJECT_SELECTED = "EXTRA_PROJECT_SELECTED"
const val COMPOSANT_NOT_SELECTED = -1
const val PROJECT_NOT_SELECTED = -1